#!/usr/bin/env python3


from sys import argv,exit,stdin
from multiprocessing import Pool
from time import sleep
from subprocess import run,PIPE,STDOUT
from io import StringIO,BytesIO
from tempfile import TemporaryFile

cmd=None
cargv=None

def work(value):
    with TemporaryFile() as tmp:
        tmp.write(value.encode('utf-8'))
        tmp.seek(0)
        p = run([ cmd ] + cargv, stdin=tmp, stdout=PIPE, stderr=STDOUT)
        p.check_returncode()

        return p.stdout.decode('utf-8')


if __name__ == "__main__":
    if len(argv) < 3:
        print(f'usage: {argv[0]} n-processes cmd arg_1 arg_2 ... arg_n')
        exit(1)

    cmd=argv[2]
    cargv=argv[3:]

    with Pool(int(argv[1])) as pool:
        for p in pool.imap_unordered(work, stdin):
            print(p, end='')

    
